# Generated by Django 3.2.5 on 2021-08-14 15:01

import cv.models_upload_to
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('last_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='last name')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='middle name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=cv.models_upload_to.cv_photo_upload_to)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('days_to_contact', models.CharField(blank=True, choices=[('all', 'All'), ('workdays', 'Workdays'), ('weekends', 'Weekends')], max_length=50, null=True, verbose_name='contact days')),
                ('time_to_contact_from', models.TimeField(blank=True, null=True, verbose_name='time to contact / from')),
                ('time_to_contact_to', models.TimeField(blank=True, null=True, verbose_name='time to contact / to')),
                ('is_resource_owner', models.BooleanField(default=False, verbose_name='resource owner')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.citizenship', verbose_name='citizenship')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.city', verbose_name='city')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.country', verbose_name='country')),
                ('physical_limitations', models.ManyToManyField(blank=True, to='dictionary.PhysicalLimitation', verbose_name='physical limitations')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_list', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CvCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='date to')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='cv.cv', verbose_name='CV')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.organization', verbose_name='customer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.position', verbose_name='position / role')),
                ('projects', models.ManyToManyField(blank=True, to='main.OrganizationProject', verbose_name='projects')),
            ],
            options={
                'verbose_name': 'career',
                'verbose_name_plural': 'career',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='CvPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cv.cv', verbose_name='CV')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.position', verbose_name='position')),
            ],
            options={
                'verbose_name': 'position / role',
                'verbose_name_plural': 'positions / roles',
                'ordering': ['id'],
                'unique_together': {('cv', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CvTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='date to')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='rate')),
                ('is_work_permit_required', models.BooleanField(default=False, verbose_name='work permit is required')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.city', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.country', verbose_name='country')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='cv.cv', verbose_name='CV')),
                ('type_of_employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.typeofemployment', verbose_name='type of employment')),
            ],
            options={
                'verbose_name': 'timeslot',
                'verbose_name_plural': 'timeslots',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='CvProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=1000, verbose_name='title')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='date to')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv.cv', verbose_name='CV')),
                ('industry_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.industrysector', verbose_name='industry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.organization', verbose_name='customer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.position', verbose_name='position / role')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='CvPositionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='file name')),
                ('file', models.FileField(upload_to=cv.models_upload_to.cv_position_file_upload_to, verbose_name='file')),
                ('cv_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cv.cvposition', verbose_name='role')),
            ],
            options={
                'verbose_name': 'role file',
                'verbose_name_plural': 'role files',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='file name')),
                ('file', models.FileField(upload_to=cv.models_upload_to.cv_file_file_upload_to, verbose_name='file')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'CV file',
                'verbose_name_plural': 'CV files',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CvEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='date to')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv.cv', verbose_name='CV')),
                ('education_graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationgraduate', verbose_name='degree')),
                ('education_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationplace', verbose_name='place of study')),
                ('education_speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationspecialty', verbose_name='specialty')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'education',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='CvCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('date', models.DateField(blank=True, null=True, verbose_name='issued')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='title')),
                ('number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('competencies', models.ManyToManyField(blank=True, to='dictionary.Competence', verbose_name='competencies')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cv.cv', verbose_name='CV')),
                ('education_graduate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationgraduate', verbose_name='degree')),
                ('education_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationplace', verbose_name='place of study')),
                ('education_speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.educationspecialty', verbose_name='specialty')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CvCareerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='file name')),
                ('file', models.FileField(upload_to=cv.models_upload_to.cv_career_file_upload_to, verbose_name='file')),
                ('cv_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cv.cvcareer', verbose_name='career')),
            ],
            options={
                'verbose_name': 'career file',
                'verbose_name_plural': 'career files',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CvContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='comment')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.contacttype', verbose_name='type')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'contact information',
                'verbose_name_plural': 'contact information',
                'ordering': ['id'],
                'unique_together': {('cv', 'contact_type', 'value')},
            },
        ),
    ]
