# Generated by Django 3.2.5 on 2021-08-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-id'], 'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AlterModelOptions(
            name='cvcareer',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'career', 'verbose_name_plural': 'career'},
        ),
        migrations.AlterModelOptions(
            name='cvcareerfile',
            options={'ordering': ['-id'], 'verbose_name': 'career file', 'verbose_name_plural': 'career files'},
        ),
        migrations.AlterModelOptions(
            name='cvcertificate',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'certificate', 'verbose_name_plural': 'certificates'},
        ),
        migrations.AlterModelOptions(
            name='cvcontact',
            options={'ordering': ['is_primary', '-id'], 'verbose_name': 'contact information',
                     'verbose_name_plural': 'contact information'},
        ),
        migrations.AlterModelOptions(
            name='cveducation',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'education',
                     'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='cvfile',
            options={'ordering': ['-id'], 'verbose_name': 'CV file', 'verbose_name_plural': 'CV files'},
        ),
        migrations.AlterModelOptions(
            name='cvposition',
            options={'ordering': ['-id'], 'verbose_name': 'position / role',
                     'verbose_name_plural': 'positions / roles'},
        ),
        migrations.AlterModelOptions(
            name='cvpositionfile',
            options={'ordering': ['-id'], 'verbose_name': 'role file', 'verbose_name_plural': 'role files'},
        ),
        migrations.AlterModelOptions(
            name='cvproject',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='cvtimeslot',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'timeslot', 'verbose_name_plural': 'timeslots'},
        ),
        migrations.AlterIndexTogether(
            name='cvcareer',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvcertificate',
            index_together={('date', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvcontact',
            index_together={('is_primary', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cveducation',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvproject',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvtimeslot',
            index_together={('date_from', 'id')},
        ),
        migrations.AddField(
            model_name='cvposition',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='arbitrary title'),
        ),
        migrations.AlterField(
            model_name='cvposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.position', verbose_name='position'),
        ),
        migrations.AddField(
            model_name='cvcareer',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='arbitrary title'),
        ),

        migrations.AlterField(
            model_name='cvcareer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    to='dictionary.position', verbose_name='position / role'),
        ),
    ]
