# Generated by Django 3.2.5 on 2021-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='пол'),
        ),
        migrations.RunSQL('''UPDATE cv_cv SET gender = 'M';'''),
    ]
