# Generated by Django 3.2.5 on 2021-08-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='доп. информация'),
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-id'], 'verbose_name': 'анкета', 'verbose_name_plural': 'анкеты'},
        ),
        migrations.AlterModelOptions(
            name='cvcareer',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'карьера', 'verbose_name_plural': 'карьера'},
        ),
        migrations.AlterModelOptions(
            name='cvcareerfile',
            options={'ordering': ['-id'], 'verbose_name': 'файл карьеры', 'verbose_name_plural': 'файлы карьеры'},
        ),
        migrations.AlterModelOptions(
            name='cvcertificate',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'сертификат', 'verbose_name_plural': 'сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='cvcontact',
            options={'ordering': ['is_primary', '-id'], 'verbose_name': 'контактные данные',
                     'verbose_name_plural': 'контактные данные'},
        ),
        migrations.AlterModelOptions(
            name='cveducation',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'образование',
                     'verbose_name_plural': 'образование'},
        ),
        migrations.AlterModelOptions(
            name='cvfile',
            options={'ordering': ['-id'], 'verbose_name': 'файл анкеты', 'verbose_name_plural': 'файлы анкеты'},
        ),
        migrations.AlterModelOptions(
            name='cvposition',
            options={'ordering': ['-id'], 'verbose_name': 'должность / роль',
                     'verbose_name_plural': 'должности / роли'},
        ),
        migrations.AlterModelOptions(
            name='cvpositionfile',
            options={'ordering': ['-id'], 'verbose_name': 'файл роли', 'verbose_name_plural': 'файлы роли'},
        ),
        migrations.AlterModelOptions(
            name='cvproject',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='cvtimeslot',
            options={'ordering': ['-date_from', '-id'], 'verbose_name': 'таймслот', 'verbose_name_plural': 'таймслоты'},
        ),
        migrations.AlterIndexTogether(
            name='cvcareer',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvcertificate',
            index_together={('date', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvcontact',
            index_together={('is_primary', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cveducation',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvproject',
            index_together={('date_from', 'id')},
        ),
        migrations.AlterIndexTogether(
            name='cvtimeslot',
            index_together={('date_from', 'id')},
        ),
        migrations.AddField(
            model_name='cvposition',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='произвольное название'),
        ),
        migrations.AlterField(
            model_name='cvposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.position', verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='cvcareer',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='произвольное название'),
        ),

        migrations.AlterField(
            model_name='cvcareer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    to='dictionary.position', verbose_name='должность / роль'),
        ),
    ]
