# Generated by Django 3.2.5 on 2021-08-10 12:08

import cv.models_upload_to
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='competencies',
        ),
        migrations.CreateModel(
            name='CvCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('years', models.FloatField(blank=True, null=True, verbose_name='опыт лет')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence', verbose_name='компетенция')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='cv.cv', verbose_name='анкета')),
            ],
            options={
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
                'ordering': ['id'],
                'unique_together': {('cv', 'competence')},
            },
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='file',
            field=models.FileField(upload_to=cv.models_upload_to.cv_file_file_upload_to, verbose_name='файл'),
        ),
    ]
