# Generated by Django 3.2.5 on 2021-08-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_round1_imports'),
        ('cv', '0002_round1_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('year_started', models.IntegerField(blank=True, null=True, verbose_name='год начала практики')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence', verbose_name='компетенция')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='cv.cv', verbose_name='анкета')),
            ],
            options={
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
                'ordering': ['-year_started', 'id'],
                'unique_together': {('cv', 'competence')},
            },
        ),
        migrations.RunSQL('INSERT INTO cv_cvcompetence (cv_id, competence_id, created_at, updated_at) '
                             'SELECT cv_id, competence_id, NOW(), NOW() FROM cv_cv_competencies'),
        migrations.RemoveField(
            model_name='cv',
            name='competencies',
        ),
    ]
