# Generated by Django 3.2.5 on 2021-09-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0002_round1_imports'),
        ('cv', '0004_round2_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvPositionCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('year_started', models.IntegerField(blank=True, null=True, verbose_name='год начала практики')),
                ('competence',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence',
                                   verbose_name='компетенция')),
            ],
            options={
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
                'ordering': ['-year_started', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='cvposition',
            name='competencies',
        ),
        migrations.DeleteModel(
            name='CvCompetence',
        ),
        migrations.AddField(
            model_name='cvpositioncompetence',
            name='cv_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies',
                                    to='cv.cvposition', verbose_name='должность / роль'),
        ),
        migrations.AlterUniqueTogether(
            name='cvpositioncompetence',
            unique_together={('cv_position', 'competence')},
        ),
        migrations.AlterModelOptions(
            name='cvpositioncompetence',
            options={'ordering': ['-year_started', 'id'], 'verbose_name': 'компетенция роли',
                     'verbose_name_plural': 'компетенции роли'},
        ),
        migrations.AddField(
            model_name='cvposition',
            name='year_started',
            field=models.IntegerField(blank=True, null=True, verbose_name='год начала практики'),
        ),
    ]
