# Generated by Django 3.2.5 on 2021-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_round2_2_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveducation',
            name='diploma_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='diploma number'),
        ),
    ]
