# Generated by Django 3.2.10 on 2022-01-04 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0016_round5'),
        ('cv', '0010_cv_import_one_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='organization_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='cv_list', to='main.organizationcontractor',
                                    verbose_name='contractor organization'),
        ),
    ]
