# Generated by Django 3.2.11 on 2022-01-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0004_round5_dict_org'),
        ('cv', '0012_round5_competence_fk_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcareer',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='dictionary.organization', verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='cvproject',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='dictionary.organization', verbose_name='заказчик'),
        ),
    ]
