# Generated by Django 3.2.11 on 2022-01-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_round5_dict_org'),
        ('cv', '0013_round5_dict_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvcareer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='cvproject',
            name='organization',
        ),
    ]
