# Generated by Django 3.2.11 on 2022-01-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_round5_dict_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvcareer',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='cvproject',
            old_name='organization_new',
            new_name='organization',
        ),
    ]
