# Generated by Django 3.2.11 on 2022-01-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0016_round5_cv_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='manager_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_list_as_rm', to=settings.AUTH_USER_MODEL, verbose_name='RM'),
        ),
    ]
