# Generated by Django 3.2.11 on 2022-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_round5_fk_2_user_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text='avoid editing if you do not know the purpose of this field', verbose_name='additional attributes'),
        ),
    ]
