# Generated by Django 3.2.5 on 2022-09-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220905_1452'),
        ('cv', '0018_alter_cv_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvcertificate',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'certificate', 'verbose_name_plural': 'certificate'},
        ),
        migrations.AlterField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='organization_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_list', to='main.organizationcontractor', verbose_name='Contractor Organization'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='time_to_contact_from',
            field=models.TimeField(blank=True, null=True, verbose_name='contact time / from'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='time_to_contact_to',
            field=models.TimeField(blank=True, null=True, verbose_name='contact time / to'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvcareer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvcareer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvcareerfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvcareerfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvpositioncompetence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvpositioncompetence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvpositionfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvpositionfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='cvtimeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='cvtimeslot',
            name='is_work_permit_required',
            field=models.BooleanField(default=False, verbose_name='work permit required'),
        ),
        migrations.AlterField(
            model_name='cvtimeslot',
            name='request_requirement_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='main.requestrequirementcv', verbose_name='linked to a request requirement'),
        ),
        migrations.AlterField(
            model_name='cvtimeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
