# Generated by Django 3.2.5 on 2022-09-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_auto_20220905_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('language', models.CharField(choices=[('english', 'English'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('german', 'German'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('turkish', 'Turkish')], max_length=8, verbose_name='language')),
                ('level', models.CharField(choices=[('A1', 'Beginner-A1'), ('A2', 'Elementary-A2'), ('B1', 'Intermediate-B1'), ('B2', 'Upper Intermediate-B2'), ('C1', 'Advanced-C1'), ('C2', 'Fluent-C2'), ('native', 'Native')], max_length=6, verbose_name='level')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.cv', verbose_name='language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
