# Generated by Django 3.2.5 on 2022-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('currency_name', models.CharField(max_length=40, verbose_name='Наименование валюты')),
                ('digital_code', models.CharField(max_length=5, verbose_name='Цифровой код')),
                ('designation', models.CharField(max_length=5, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Справочник Валюты',
                'verbose_name_plural': 'Справочники Валют',
            },
        ),
    ]
