# Generated by Django 3.2.5 on 2021-08-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'citizenship',
                'verbose_name_plural': 'citizenships',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'contact type',
                'verbose_name_plural': 'contact types',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['sorting', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationGraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'academic degree',
                'verbose_name_plural': 'academic degrees',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'place of study',
                'verbose_name_plural': 'places of study',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'specialty',
                'verbose_name_plural': 'specialties',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'physical limitation',
                'verbose_name_plural': 'physical limitations',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
            ],
            options={
                'verbose_name': 'type of employment',
                'verbose_name_plural': 'types of employment',
                'ordering': ['sorting', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.competence', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'competence',
                'verbose_name_plural': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dictionary.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['sorting', 'name'],
            },
        ),
    ]
