# Generated by Django 3.2.5 on 2021-08-20 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='competence',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='проверено'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='educationgraduate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='educationplace',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='educationspecialty',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='industrysector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='industrysector',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='physicallimitation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='physicallimitation',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AddField(
            model_name='typeofemployment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='typeofemployment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
    ]
