# Generated by Django 3.2.5 on 2022-08-30 14:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_round1_imports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenship',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'гражданство', 'verbose_name_plural': 'гражданства'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'компетенция', 'verbose_name_plural': 'компетенции'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'тип контактной информации', 'verbose_name_plural': 'типы контактной информации'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
        migrations.AlterModelOptions(
            name='educationgraduate',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'ученая степень', 'verbose_name_plural': 'ученые степени'},
        ),
        migrations.AlterModelOptions(
            name='educationplace',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'место учебы', 'verbose_name_plural': 'места учебы'},
        ),
        migrations.AlterModelOptions(
            name='educationspecialty',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'специальность', 'verbose_name_plural': 'специальности'},
        ),
        migrations.AlterModelOptions(
            name='industrysector',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'отрасль', 'verbose_name_plural': 'отрасли'},
        ),
        migrations.AlterModelOptions(
            name='physicallimitation',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'физическая особенность', 'verbose_name_plural': 'физические особенности'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'должность', 'verbose_name_plural': 'должности'},
        ),
        migrations.AlterModelOptions(
            name='typeofemployment',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'тип занятости', 'verbose_name_plural': 'типы занятости'},
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dictionary.country', verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.competence', verbose_name='родитель'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
