# Generated by Django 3.2.11 on 2022-01-19 16:15

from django.db import migrations, models


def f(apps, schema_editor):
    main_organization = apps.get_model('main', 'Organization')
    dict_organization = apps.get_model('dictionary', 'Organization')
    for o in main_organization.objects.all():
        dict_organization.objects.create(
            name=o.name,
            old_id=o.id,
        )
    main_organization.objects.filter(is_customer=False, is_contractor=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0004_round5_dict_org'),
        ('cv', '0013_round5_dict_org'),
    ]

    operations = [
        migrations.RunSQL('''
INSERT INTO dictionary_organization 
    (name, old_id, created_at, updated_at, is_verified, sorting) 
SELECT 
    name, id, NOW(), NOW(), FALSE, 0
FROM main_organization
;

UPDATE cv_cvcareer 
SET organization_new_id = _.new_org_id
FROM (
    SELECT 
        _.id, 
        __.id AS new_org_id
    FROM 
        cv_cvcareer AS _
        JOIN dictionary_organization AS __ ON TRUE
            AND __.old_id = _.organization_id 
) AS _
WHERE true
    AND cv_cvcareer.id = _.id
;

UPDATE cv_cvproject
SET organization_new_id = _.new_org_id
FROM (
    SELECT 
        _.id, 
        __.id AS new_org_id
    FROM 
        cv_cvproject AS _
        JOIN dictionary_organization AS __ ON TRUE
            AND __.old_id = _.organization_id 
) AS _
WHERE true
    AND cv_cvproject.id = _.id
;


        ''')
    ]
