# Generated by Django 3.2.11 on 2022-01-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_round5_dict_org'),
        ('dictionary', '0005_round5_dict_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='old_id',
        ),
    ]
