# Generated by Django 3.2.5 on 2022-09-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20220830_1740'),
        ('dictionary', '0007_attributes'),
    ]

    operations = [
    ]
