# Generated by Django 3.2.5 on 2022-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_merge_0003_auto_20220830_1740_0007_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='название')),
                ('is_verified', models.BooleanField(default=False, verbose_name='подтверждено')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('sorting', models.IntegerField(default=0, verbose_name='сортировка')),
                ('attributes', models.JSONField(default=dict, editable=False, help_text='если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования', verbose_name='доп. атрибуты')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='название')),
                ('is_verified', models.BooleanField(default=False, verbose_name='подтверждено')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('sorting', models.IntegerField(default=0, verbose_name='сортировка')),
                ('attributes', models.JSONField(default=dict, editable=False, help_text='если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования', verbose_name='доп. атрибуты')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificate',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='название'),
        ),
    ]
