# Generated by Django 3.2.5 on 2022-09-06 10:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20220905_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenship',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'citizenship', 'verbose_name_plural': 'citizenships'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'competence', 'verbose_name_plural': 'competences'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'contact info type', 'verbose_name_plural': 'contact info types'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='educationgraduate',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'science degree', 'verbose_name_plural': 'science degree'},
        ),
        migrations.AlterModelOptions(
            name='educationplace',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'education place', 'verbose_name_plural': 'education places'},
        ),
        migrations.AlterModelOptions(
            name='educationspecialty',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'specialty', 'verbose_name_plural': 'specialties'},
        ),
        migrations.AlterModelOptions(
            name='industrysector',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'sector', 'verbose_name_plural': 'sectors'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='physicallimitation',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'disability', 'verbose_name_plural': 'disabilities'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'position', 'verbose_name_plural': 'positions'},
        ),
        migrations.AlterModelOptions(
            name='typeofemployment',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'employment type', 'verbose_name_plural': 'employment types'},
        ),
        migrations.AlterField(
            model_name='category',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='city',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dictionary.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionary.competence', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='country',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='educationgraduate',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='educationplace',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='educationspecialty',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='physicallimitation',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='position',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='attributes',
            field=models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='typeofemployment',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='sorting'),
        ),
    ]
