# Generated by Django 3.2.5 on 2022-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20220906_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='title')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('attributes', models.JSONField(default=dict, editable=False, help_text=" if you don't really understand purpose of this field you should avoid editing", verbose_name='additional attributes')),
                ('currency_name', models.CharField(max_length=40, verbose_name='Currency name')),
                ('digital_code', models.CharField(max_length=5, verbose_name='Digital code')),
                ('designation', models.CharField(max_length=5, verbose_name='Designation')),
                ('currency_link', models.CharField(max_length=255, verbose_name='Currency link')),
            ],
            options={
                'verbose_name': 'Currency reference',
                'verbose_name_plural': 'Currency references',
                'ordering': ['sorting', 'name'],
            },
        ),
    ]
