import os

REDIS_HOST = os.environ.get('REDIS_HOST') or 'redis'
REDIS_PORT = os.environ.get('REDIS_PORT') or 6379
REDIS_CONNECT_RETRY = True

REDIS_ENABLED = True

REDIS_DB_SESSION = 1
REDIS_DB_CACHE_DEFAULT = 2
REDIS_DB_CACHE_SELECT2 = 3
REDIS_DB_CACHE_CACHEOPS = 4
REDIS_DB_CELERY = 5
