# Generated by Django 3.2.5 on 2022-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_round5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersystemrole',
            options={'verbose_name': 'system role', 'verbose_name_plural': 'system roles'},
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мale'), ('F', 'Female'), ('-', 'Other')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='usersystemrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pfm', 'Project portfolio manager'), ('pm', 'Project manager'), ('rm', 'Resource manager')], max_length=50),
        ),
    ]
