# Generated by Django 3.2.5 on 2021-08-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0002_round1_imports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=500, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('recruiters', models.ManyToManyField(related_name='projects_as_recruiter', to=settings.AUTH_USER_MODEL,
                                                      verbose_name='рекрутеры')),
                ('resource_managers',
                 models.ManyToManyField(related_name='projects_as_resource_manager', to=settings.AUTH_USER_MODEL,
                                        verbose_name='ресурсные менеджеры')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('status', models.CharField(
                    choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('done', 'Успешно завершен'),
                             ('closed', 'Закрыт')], default='draft', max_length=50, verbose_name='статус')),
                ('priority',
                 models.CharField(choices=[('major', 'Высокий'), ('default', 'Обычный'), ('minor', 'Низкий')],
                                  default='default', max_length=50, verbose_name='приоритет')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='срок')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests',
                                               to='main.organization', verbose_name='заказчик')),
                ('industry_sector',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests', to='dictionary.industrysector', verbose_name='отрасль')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                              related_name='requests', to='main.project', verbose_name='проект')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                                related_name='requests_as_recruiter', to=settings.AUTH_USER_MODEL,
                                                verbose_name='отв. рекрутер')),
                ('resource_manager',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests_as_resource_manager', to=settings.AUTH_USER_MODEL,
                                   verbose_name='рес. менеджер')),
            ],
            options={
                'verbose_name': 'проектный запрос',
                'verbose_name_plural': 'проектные запросы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('sorting', models.IntegerField(default=0, verbose_name='сортировка')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('experience_years',
                 models.FloatField(blank=True, help_text='float', null=True, verbose_name='опыт лет')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('work_location_address',
                 models.CharField(blank=True, max_length=1000, null=True, verbose_name='адрес')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='макс. цена')),
                ('position',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests_requirements',
                                   to='dictionary.position', verbose_name='должность')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements',
                                              to='main.request', verbose_name='запрос')),
                ('type_of_employment',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests_requirements', to='dictionary.typeofemployment',
                                   verbose_name='тип занятости')),
                ('work_location_city',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='requests_requirements', to='dictionary.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'требование проектного запроса',
                'verbose_name_plural': 'требования проектного запроса',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип проектного запроса',
                'verbose_name_plural': 'типы проектных запросов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organizationproject',
            options={'ordering': ['name'], 'verbose_name': 'проект организации',
                     'verbose_name_plural': 'проекты организаций'},
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects',
                                    to='main.organization', verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='requests', to='main.requesttype', verbose_name='тип запроса'),
        ),
        migrations.CreateModel(
            name='RequestRequirementCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('experience_years', models.IntegerField(blank=True, choices=[(1, 'Менее года'), (3, '1 – 3 года'),
                                                                              (5, '3 - 5 лет'), (100, 'Более 5 лет')],
                                                         null=True, verbose_name='опыт лет')),
                ('sorting', models.IntegerField(default=0, verbose_name='сортировка')),
                ('competence',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence',
                                   verbose_name='компетенция')),
                ('request_requirement',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies',
                                   to='main.requestrequirement', verbose_name='требование проектного запроса')),
            ],
            options={
                'verbose_name': 'компетенция',
                'verbose_name_plural': 'компетенции',
                'ordering': ['sorting', '-experience_years', 'id'],
                'unique_together': {('request_requirement', 'competence')},
            },
        ),

        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority', '-id'], 'verbose_name': 'проектный запрос',
                     'verbose_name_plural': 'проектные запросы'},
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.IntegerField(choices=[(10, 'Высокий'), (20, 'Обычный'), (30, 'Низкий')], default=20,
                                      verbose_name='приоритет'),
        ),

        migrations.AlterField(
            model_name='requestrequirement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    related_name='requests_requirements', to='dictionary.position',
                                    verbose_name='должность'),
        ),
    ]
