# Generated by Django 3.2.5 on 2021-08-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0002_round1_imports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('recruiters', models.ManyToManyField(related_name='projects_as_recruiter', to=settings.AUTH_USER_MODEL,
                                                      verbose_name='recruiters')),
                ('resource_managers',
                 models.ManyToManyField(related_name='projects_as_resource_manager', to=settings.AUTH_USER_MODEL,
                                        verbose_name='resource managers')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(
                    choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('done', 'Successfully completed'),
                             ('closed', 'Closed')], default='draft', max_length=50, verbose_name='status')),
                ('priority',
                 models.CharField(choices=[('major', 'Major'), ('default', 'Default'), ('minor', 'Minor')],
                                  default='default', max_length=50, verbose_name='priority')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests',
                                               to='main.organization', verbose_name='customer')),
                ('industry_sector',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests', to='dictionary.industrysector', verbose_name='industry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                              related_name='requests', to='main.project', verbose_name='проект')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                                related_name='requests_as_recruiter', to=settings.AUTH_USER_MODEL,
                                                verbose_name='recruiter')),
                ('resource_manager',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests_as_resource_manager', to=settings.AUTH_USER_MODEL,
                                   verbose_name='resource manager')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('experience_years',
                 models.FloatField(blank=True, help_text='float', null=True, verbose_name='years of experience')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='count')),
                ('work_location_address',
                 models.CharField(blank=True, max_length=1000, null=True, verbose_name='address')),
                ('max_price', models.FloatField(blank=True, null=True, verbose_name='max rate')),
                ('position',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests_requirements',
                                   to='dictionary.position', verbose_name='position')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements',
                                              to='main.request', verbose_name='запрос')),
                ('type_of_employment',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   related_name='requests_requirements', to='dictionary.typeofemployment',
                                   verbose_name='type of employment')),
                ('work_location_city',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='requests_requirements', to='dictionary.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'request requirement',
                'verbose_name_plural': 'request requirements',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
            ],
            options={
                'verbose_name': 'request type',
                'verbose_name_plural': 'request types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='organizationproject',
            options={'ordering': ['name'], 'verbose_name': 'organization\'s project',
                     'verbose_name_plural': 'organization\'s projects'},
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects',
                                    to='main.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='requests', to='main.requesttype', verbose_name='request type'),
        ),
        migrations.CreateModel(
            name='RequestRequirementCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('experience_years', models.IntegerField(blank=True, choices=[(1, 'Less than a year'), (3, '1 – 3 years'),
                                                                              (5, '3 - 5 years'), (100, 'More than 5 years')],
                                                         null=True, verbose_name='years of experience')),
                ('sorting', models.IntegerField(default=0, verbose_name='sorting')),
                ('competence',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence',
                                   verbose_name='competence')),
                ('request_requirement',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies',
                                   to='main.requestrequirement', verbose_name='request requirement')),
            ],
            options={
                'verbose_name': 'competence',
                'verbose_name_plural': 'competencies',
                'ordering': ['sorting', '-experience_years', 'id'],
                'unique_together': {('request_requirement', 'competence')},
            },
        ),

        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority', '-id'], 'verbose_name': 'request',
                     'verbose_name_plural': 'requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.IntegerField(choices=[(10, 'Major'), (20, 'Default'), (30, 'Minor')], default=20,
                                      verbose_name='priority'),
        ),

        migrations.AlterField(
            model_name='requestrequirement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                    related_name='requests_requirements', to='dictionary.position',
                                    verbose_name='position'),
        ),
    ]
