# Generated by Django 3.2.5 on 2021-08-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_round2'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
