# Generated by Django 3.2.5 on 2021-09-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='заказчик?'),
        ),
        migrations.AddField(
            model_name='requestrequirement',
            name='cv_list',
            field=models.ManyToManyField(blank=True, to='cv.CV', verbose_name='анкеты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(help_text='организации отмеченные как заказчики', limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.organization', verbose_name='заказчик'),
        ),
    ]
