# Generated by Django 3.2.5 on 2022-08-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20220830_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0006_auto_20220830_1740'),
        ('main', '0004_round2_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationproject',
            options={'ordering': ['name'], 'verbose_name': 'проект организации', 'verbose_name_plural': 'проекты организаций'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority', '-id'], 'verbose_name': 'проектный запрос', 'verbose_name_plural': 'проектные запросы'},
        ),
        migrations.AlterModelOptions(
            name='requestrequirement',
            options={'ordering': ['sorting', 'name'], 'verbose_name': 'требование проектного запроса', 'verbose_name_plural': 'требования проектного запроса'},
        ),
        migrations.AlterModelOptions(
            name='requestrequirementcompetence',
            options={'ordering': ['sorting', '-experience_years', 'id'], 'verbose_name': 'компетенция', 'verbose_name_plural': 'компетенции'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'ordering': ['name'], 'verbose_name': 'тип проектного запроса', 'verbose_name_plural': 'типы проектных запросов'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='заказчик?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.organization', verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recruiters',
            field=models.ManyToManyField(related_name='projects_as_recruiter', to=settings.AUTH_USER_MODEL, verbose_name='рекрутеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_managers',
            field=models.ManyToManyField(related_name='projects_as_resource_manager', to=settings.AUTH_USER_MODEL, verbose_name='ресурсные менеджеры'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(help_text='организации отмеченные как заказчики', limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.organization', verbose_name='заказчик'),
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='срок'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='industry_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='dictionary.industrysector', verbose_name='отрасль'),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.IntegerField(choices=[(10, 'Высокий'), (20, 'Обычный'), (30, 'Низкий')], default=20, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='request',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_as_recruiter', to=settings.AUTH_USER_MODEL, verbose_name='отв. рекрутер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resource_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_as_resource_manager', to=settings.AUTH_USER_MODEL, verbose_name='рес. менеджер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('done', 'Успешно завершен'), ('closed', 'Закрыт')], default='draft', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.requesttype', verbose_name='тип запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='cv_list',
            field=models.ManyToManyField(blank=True, to='cv.CV', verbose_name='анкеты'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='experience_years',
            field=models.FloatField(blank=True, help_text='float', null=True, verbose_name='опыт лет'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='max_price',
            field=models.FloatField(blank=True, null=True, verbose_name='макс. цена'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_requirements', to='dictionary.position', verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='type_of_employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_requirements', to='dictionary.typeofemployment', verbose_name='тип занятости'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='work_location_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='requestrequirement',
            name='work_location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_requirements', to='dictionary.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.competence', verbose_name='компетенция'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='experience_years',
            field=models.IntegerField(blank=True, choices=[(1, 'Менее года'), (3, '1 – 3 года'), (5, '3 - 5 лет'), (100, 'Более 5 лет')], null=True, verbose_name='опыт лет'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='request_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='main.requestrequirement', verbose_name='требование проектного запроса'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='sorting',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=500, verbose_name='название'),
        ),
    ]
