# Generated by Django 3.2.5 on 2021-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_round2_2_2'),
        ('main', '0004_round2_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrequirement',
            name='cv_list',
            field=models.ManyToManyField(blank=True, related_name='requests_requirements', to='cv.CV', verbose_name='CVs'),
        ),
    ]
