# Generated by Django 3.2.5 on 2021-10-02 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cveducation_diploma_number'),
        ('main', '0006_round3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrequirement',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.request', verbose_name='проектный запрос'),
        ),
        migrations.CreateModel(
            name='TimeSheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('date_from', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='дата начала работ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='дата окончания работ')),
                ('task_name', models.CharField(max_length=1000, verbose_name='задача')),
                ('work_time', models.FloatField(verbose_name='затраченное время')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='time_sheet_rows', to='cv.cv', verbose_name='анкета исполнителя')),
                ('request_requirement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='time_sheet_rows', to='main.requestrequirement', verbose_name='требование проектного запроса')),
            ],
            options={
                'verbose_name': 'строка таймшита',
                'verbose_name_plural': 'строки таймшитов',
                'ordering': ['-date_from'],
                'index_together': {('request_requirement', 'task_name'), ('request_requirement', 'date_from')},
            },
        ),
        migrations.AddField(
            model_name='timesheetrow',
            name='task_description',
            field=models.TextField(blank=True, null=True, verbose_name='описание задачи'),
        ),
        migrations.AlterField(
            model_name='timesheetrow',
            name='task_name',
            field=models.CharField(max_length=1000, verbose_name='название задачи'),
        ),

        migrations.AddField(
            model_name='request',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='заголовок (название или номер)'),
        ),
    ]
