# Generated by Django 3.2.5 on 2021-11-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_round4'),
    ]

    operations = [
        migrations.RunSQL('TRUNCATE main_request CASCADE'),
        migrations.RemoveField(
            model_name='request',
            name='organization_project',
        ),
        migrations.AddField(
            model_name='request',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests',
                                    to='main.module', verbose_name='модуль'),
            preserve_default=False,
        ),
    ]
