# Generated by Django 3.2.5 on 2021-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_round4'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproject',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='goals'),
        ),
        migrations.AddField(
            model_name='organizationproject',
            name='plan_description',
            field=models.TextField(blank=True, null=True, verbose_name='resource plan'),
        ),
    ]
