# Generated by Django 3.2.11 on 2022-01-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_name_indexes'),
        ('main', '0017_round5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontractoruserrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('pfm', 'Руководитель портфеля проектов'), ('pm', 'Руководитель проекта'), ('rm', 'Ресурсный менеджер')], max_length=50, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='organizationprojectuserrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('pfm', 'Руководитель портфеля проектов'), ('pm', 'Руководитель проекта'), ('rm', 'Ресурсный менеджер')], max_length=50, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='requestrequirementcompetence',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.competence', verbose_name='компетенция'),
        ),
    ]
