# Generated by Django 3.2.11 on 2022-01-13 15:23

from django.db import migrations, models
import django.db.models.deletion


def f(apps, schema_editor):
    OrganizationProject = apps.get_model("main", "OrganizationProject")
    OrganizationCustomer = apps.get_model("main", "OrganizationCustomer")
    customer = OrganizationCustomer.objects.filter(id=42977).first() or OrganizationCustomer.objects.first()
    OrganizationProject.objects.update(organization_customer=customer)


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_round5_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contractor',
        ),
        migrations.AddField(
            model_name='organizationproject',
            name='organization_contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects_as_contractor', to='main.organizationcontractor',
                                    verbose_name='contractor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='organization_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_customer',
                                    to='main.organizationcustomer', verbose_name='customer'),
        ),
    ]
