# Generated by Django 3.2.11 on 2022-01-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_round5_dict_org'),
        ('cv', '0015_round5_dict_org'),
        ('main', '0020_round5_permissions'),
    ]

    operations = [
        migrations.RunSQL('''
DELETE FROM main_organization WHERE NOT is_customer AND NOT is_contractor 
        ''')
    ]
