# Generated by Django 3.2.11 on 2022-01-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_round5_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationproject',
            name='manager',
        ),
        migrations.AddField(
            model_name='organizationproject',
            name='manager_pfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organizations_projects_as_pfm', to=settings.AUTH_USER_MODEL, verbose_name='PPM'),
        ),
        migrations.AddField(
            model_name='organizationproject',
            name='manager_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organizations_projects_as_pm', to=settings.AUTH_USER_MODEL, verbose_name='PM'),
        ),
    ]
