# Generated by Django 3.2.11 on 2022-01-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_round5_request_rm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='request',
            name='resource_manager',
        ),
        migrations.AlterField(
            model_name='module',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='manager_pfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_projects_as_pfm', to=settings.AUTH_USER_MODEL, verbose_name='PPM'),
        ),
        migrations.AlterField(
            model_name='organizationproject',
            name='manager_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_projects_as_pm', to=settings.AUTH_USER_MODEL, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='request',
            name='manager_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_as_rm', to=settings.AUTH_USER_MODEL, verbose_name='RM'),
        ),
    ]
