# Generated by Django 3.2.12 on 2022-02-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_round5_fk_request_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('done', 'Successfully completed'), ('closed', 'Closed')], default='draft', max_length=50, verbose_name='status'),
        ),
    ]
