# Generated by Django 3.2.12 on 2022-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0027_round5_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrequirement',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In progress'),
                                            ('done', 'Successfully completed')], default='open', max_length=50,
                                   verbose_name='status'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='manager',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_person',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='contact person'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contacts_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contacts_phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='organization',
            name='general_manager_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='general manager'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='is a partner?'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='legal name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='short name'),
        ),
    ]
