# Generated by Django 3.2.12 on 2022-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_round5_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrequirement',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('in_progress', 'В работе'), ('done', 'Успешно завершен')], default='open', max_length=50, verbose_name='статус'),
        ),
    ]
