# Generated by Django 3.2.5 on 2022-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220905_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontractoruserrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pfm', 'Project portfolio manager'), ('pm', 'Project manager'), ('rm', 'Resource manager')], max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='organizationprojectuserrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('pfm', 'Project portfolio manager'), ('pm', 'Project manager'), ('rm', 'Resource manager')], max_length=50, verbose_name='role'),
        ),
    ]
