# Generated by Django 3.2.5 on 2022-09-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20220906_1337'),
        ('main', '0030_auto_20220906_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='network',
        ),
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.organization', verbose_name='partners'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnernetwork',
            name='partners',
            field=models.ManyToManyField(to='main.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name="partner's name"),
        ),
        migrations.AlterField(
            model_name='partnernetwork',
            name='name',
            field=models.CharField(max_length=255, verbose_name='network name'),
        ),
    ]
