# Generated by Django 3.2.5 on 2022-09-07 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20220907_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='services_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('OUTSOURCE', 'Outsource'), ('OUTSTAFF', 'Outstaff'), ('BOTH', 'Both')], max_length=255, null=True, verbose_name='services_type'), size=None),
        ),
    ]
