# Generated by Django 3.2.5 on 2022-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_partner_services_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='services_type',
            field=models.CharField(blank=True, choices=[('OUTSOURCE', 'Outsource'), ('OUTSTAFF', 'Outstaff'), ('BOTH', 'Both')], max_length=255, null=True, verbose_name='services_type'),
        ),
    ]
