# Generated by Django 3.2.5 on 2022-09-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_currencyreference'),
        ('main', '0034_alter_partner_services_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='partnernetwork',
            options={'verbose_name': 'partner network', 'verbose_name_plural': 'partner networks'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='is_accredited',
            field=models.BooleanField(default=False, verbose_name='is accredited'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='is blocked'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='certificate',
            field=models.ManyToManyField(related_name='certificates', to='dictionary.Certificate', verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='competence',
            field=models.ManyToManyField(related_name='competences', to='dictionary.Competence', verbose_name='competence'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partners', to='dictionary.organization', verbose_name='partners'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partners', to='dictionary.industrysector', verbose_name='segment'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='services_type',
            field=models.CharField(choices=[('OUTSOURCE', 'Outsource'), ('OUTSTAFF', 'Outstaff'), ('BOTH', 'Both')], default='OUTSTAFF', max_length=255, verbose_name='services_type'),
        ),
        migrations.AlterField(
            model_name='partnernetwork',
            name='network_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='networks', to='dictionary.organization', verbose_name='network_operator'),
        ),
        migrations.AlterField(
            model_name='partnernetwork',
            name='partners',
            field=models.ManyToManyField(related_name='partners', to='main.Partner', verbose_name='partners'),
        ),
    ]
